site_name: oneFace Docs

repo_url: https://github.com/Nanguage/oneFace

theme: material

nav:
  - Home: index.md
  - Basic Usage: basic_usage.md
  - Built-in Types: builtin_types.md
  - Type Extension: type_extension.md
  - Interface configuration:
    - Qt configs: qt_confs.md
    - Dash configs: dash_confs.md
  - Wrap command line: wrap_cli.md
  - Embedding:
    - dash_embed.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
