site_name: oneFace Docs

repo_url: https://github.com/Nanguage/oneFace

theme: material

nav:
  - Home: index.md
  - Basic Usage: basic_usage.md
  - Built-in Types: builtin_types.md
  - Type Extension: type_extension.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
