site_name: oneFace Docs

repo_url: https://github.com/Nanguage/oneFace

theme: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
